# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kcrash': '@stable'
    'frameworks/ksonnet': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/kconfigwidgets': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/kdoctools': '@stable'
    'frameworks/kio': '@stable'
    'frameworks/knewstuff': '@stable'
    'kdeedu/libkeduvocdocument': '@same'
